### ISSUE TITLE
Background Element Misalignment on Horizontal Resize

### ISSUE THREAD

**Issue by morzsiHUN** [SzaboKolos/embroidery_calculator#12]
### Description:
When resizing the page horizontally, one of the background element fails to align correctly. This issue only appears, when the aspect ratio decreases from 16:9 to a narrower ratio, transitioning between desktop and mobile device modes.

### Environment:

- Browser: Firefox 125.0.1 (64 bit)
- Application Version: 3.2.29-BETA

### Screenshots:
![kép](https://github.com/SzaboKolos/embroidery_calculator/assets/75016954/1933ff5a-1498-4f32-afe3-47ae4bc133fd)
![kép](https://github.com/SzaboKolos/embroidery_calculator/assets/75016954/a97a9ef5-1765-4889-81ed-5109131c5799)

**Comment by SzaboKolos** [comment]
fixed in 3.2.31-BETA
